# Generated by Django 4.2.2 on 2023-09-15 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cad_instrutor',
            fields=[
                ('id_instrutor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('edv', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=150)),
                ('cor', models.CharField(max_length=20)),
                ('materias', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='cad_sala',
            fields=[
                ('id_sala', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_sala', models.CharField(max_length=20)),
                ('predio_sala', models.CharField(choices=[('1', 'Ca600-ETS'), ('2', 'Ca170-ETS'), ('3', 'Ca140-ETS')], default=1, max_length=1)),
                ('localizacao_sala', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField(default=0)),
                ('computador', models.IntegerField(default=0)),
                ('quadro_branco', models.IntegerField(default=0)),
                ('projetor', models.IntegerField(default=0)),
                ('televisao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_Evento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_responsavel', models.CharField(max_length=250)),
                ('nome_evento', models.CharField(max_length=100)),
                ('edv_cliente', models.IntegerField()),
                ('descricao', models.CharField(max_length=500)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('local', models.CharField(max_length=20)),
                ('nome_sala', models.CharField(max_length=20)),
                ('historico', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagem', models.ImageField(upload_to='imagens/')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cadastro.cad_sala')),
            ],
        ),
    ]
