# Generated by Django 4.2.3 on 2023-10-15 21:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api_cadastro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id_sala",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome_sala", models.CharField(max_length=20)),
                (
                    "predio_sala",
                    models.CharField(
                        choices=[
                            ("Ca600", "Ca600"),
                            ("Ca170", "Ca170"),
                            ("Ca140", "Ca140"),
                        ],
                        max_length=5,
                    ),
                ),
                ("localizacao_sala", models.CharField(max_length=100)),
                ("capacidade", models.IntegerField(default=0)),
                ("computador", models.IntegerField(default=0)),
                ("quadro_branco", models.IntegerField(default=0)),
                ("projetor", models.IntegerField(default=0)),
                ("televisao", models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name="cad_instrutor",
            new_name="Instrutor",
        ),
        migrations.AlterField(
            model_name="imagem",
            name="Imagem",
            field=models.ImageField(upload_to="static/img/"),
        ),
        migrations.AlterField(
            model_name="imagem",
            name="sala",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api_cadastro.sala"
            ),
        ),
        migrations.DeleteModel(
            name="cad_sala",
        ),
    ]
