# Generated by Django 4.2.3 on 2023-10-17 01:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_cadastro", "0005_evento_materia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="nome_evento",
        ),
    ]
