# Generated by Django 4.2.3 on 2023-10-17 01:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_cadastro", "0006_remove_evento_nome_evento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="id_evento",
            new_name="id_Evento",
        ),
    ]
