# Generated by Django 4.2.3 on 2024-03-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cadastro', '0007_rename_id_evento_evento_id_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edv', models.CharField(max_length=8)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
